#!/bin/bash     
#title          :aufgaben1_1
#description    :Lösungsvorschläge zu Aufgaben 1.1
#author         :Jochen Reinholdt
#date           :20180618
#version        :1      
#usage          :./aufgabe1_1
#notes          :       
#bash_version   :3.2.57(1)-release
#============================================================================

# a)
ps -ef | grep cron

# b)
ps -ef | grep root

# c)
ps -ef | grep -v root

# d)
ps -ef | grep cron | grep -v grep

# e)
ps -ef | grep root | grep -v grep | wc -l

# f)
ps -ef > psout
grep cron psout
grep -v root psout
grep root psout | wc -l # usw.

# g)
ps -ef | sort

# h)
ps -ef | sort -k2

# i)
ps -ef | sort -n -k2

# j)
sort -n -k2 psout
sort -n -k2 < psout # usw.
