#!/bin/bash     
#title          :aufgaben1_4
#description    :Lösungen zu Aufgaben 1.4
#author         :Jochen Reinholdt
#date           :20180618
#version        :1      
#usage          :./aufgaben1_4
#notes          :       
#bash_version   :3.2.57(1)-release
#============================================================================

# a)
cut -d: -f1,6,7 /etc/passwd

# b)
cut -d: -f1,6,7 /etc/passwd | tr : -

# c)
cut -d: -f1,6,7 /etc/passwd | tr : " "

# d)
sed 's/:.*:/ /' /etc/passwd
# oder
sed 's/:[^:]*$//;s/:.*:/ /' /etc/passwd

# e)
sed 's/:[^/]*:/ hat das Heimatverzeichnis /; s/:/, die Shell ist /' /etc/passwd

# Das gleicheche mit einem sed-skript mit dem Inhalt:
#
# s/:[^/]*:/ hat das Heimatverzeichnis /; 
# s/:/, die Shell ist /
#
sed -f sed-script /etc/passwd

# f)
sed 's/^./\U/' /etc/passwd
