#!/bin/bash     
#title          :backupd3
#description    :Backup-Kopie eines Quellverzeichnisses $1 unterhalb
#		 eines Zielverzeichnisses, das entweder durch $BACKDIR 
#	         vorgegeben ist, oder alternativ im aktuellen Verzeichnis
#author         :Jochen Reinholdt
#date           :20180618
#version        :1      
#usage          :./backupd3
#notes          :       
#bash_version   :3.2.57(1)-release
#============================================================================

# Wenn BACKDIR nicht gesetzt oder leer ist, wird als Default 
# für die Variable . genommen
zielpfad=${BACKDIR:=.}

# basename liefert den letzten Teil des Pfads in $1
# Kommandosubstitution wird benutzt
# Vor den Namen des Quellverzeichnisses wird / gesetzt
quellname=/`basename $1`

# Kommandosubstitution: Ausgabe von date
datum=`date +%Y_%m_%d`

zielname=$quellname.$datum

cp -R $1  $zielpfad$zielname

