#!/bin/bash     
#title          :backupd1
#description    :Erzeugt eine Kopie des Verzeichnisse, das als 
#                1. Parameter angegeben ist unter dem Pfad,
#                der durch den 2. Parameter angegeben ist
#                An den Namen des Zielverzeichnisses wird .bak angehängt
#author         :Jochen Reinholdt
#date           :20180618
#version        :1      
#usage          :./backupd1
#notes          :       
#bash_version   :3.2.57(1)-release
#============================================================================

dir=`basename $1`
# alternativ: dir=$(basename $1)

cp -R $1  $2\/$dir.bak

