#!/bin/bash     
#title          :chkdf1a
#description    :Variante zu chkdf1 (siehe auch Kommentare dort) nur mit awk
#author         :Jochen Reinholdt
#date           :20180823
#version        :1.0    
#usage          :chkdf1a
#notes          :       
#bash_version   :4.4.12(1)-release
#============================================================================

threshold=$1

# NR>1 im awk-Skript überspringt die 1. Zeile, gsub() ersetzt das %-Zeichen durch nichts
for line in $(df -k | awk 'NR>1 {gsub("%",""); print $6 ":" $5 }')
do
	dir="${line%:*}"
	pct="${line#*:}"

    if [ $pct -gt threshold ]
    then
        echo Filesystem $dir ist zu ${pct}% voll!
    fi
done
