#!/bin/bash     
#title          :chkdf1b
#description    :Variante zu chkdf1 (siehe auch Kommentare dort) nur mit sed
#author         :Jochen Reinholdt
#date           :20180823
#version        :1.0    
#usage          :chkdf1b
#notes          :       
#bash_version   :4.4.12(1)-release
#============================================================================

threshold=$1

# Variante mit tr, cut und sed
for line in $( df -k | tr -s ' ' | cut -d' ' -f5,6 | sed -n '2,$ s/% /:/ p')
do
	pct=${line%:*}
    dir=${line#*:}

    if [ $pct -gt threshold ]
    then
        echo Filesystem $dir ist zu ${pct}% voll!
    fi
done
