#!/bin/bash     
#title          :chkdf1b
#description    :Variante zu chkdf1 (siehe auch Kommentare dort) nur mit sed
#author         :Jochen Reinholdt
#date           :20180823
#version        :1.0    
#usage          :chkdf1b
#notes          :       
#bash_version   :4.4.12(1)-release
#============================================================================

declare -A map

# Variante mit tr, cut und sed
for line in $( df -k | tr -s ' ' | cut -d' ' -f5,6 | sed -n '2,$ s/% /:/ p')
do
	pct=${line%:*}
    dir=${line#*:}
	map[$dir]=$pct
done

# Ausgabe des Array map
for key in ${!map[@]}
do
	echo mountpoint: $key % verwendet: ${map[$key]}
done
