#!/bin/bash     
#title          :chkdf1  
#description    :Wertet die Spalten 5 (%verwendet)  und 6 (mount-point) in der Ausgabe von df aus. 
#author         :Jochen Reinholdt
#date           :20180823
#version        :1.0    
#usage          :chkdf1
#notes          :       
#bash_version   :4.4.12(1)-release
#============================================================================

threshold=$1

# Wir benötigen die Werte 6. und 5. Spalte der Ausgabe von df -k 
# (je ein Dateisystem und sein Füllungsgrad in %) nach entfernen der Überschriften
# und des %-Zeichens. Zeichen ':' wird als Trenner dazwischen eingefügt

for line in $(df -k | tail --lines=+2 | tr -d '%' | awk '{print $6 ":" $5}')
do
    # Jede Zeile hat jetzt das Format Filesystem:Füllungsgrad

	# Dann wird bash Parameter Expansion verwendet um die beiden Werte auszuschneiden. 
	# Alternativ wäre das auch mit sed möglich
	# ${VARIABLE%MUSTER} entfernt MUSTER vom Ende des Textes in VARIABLE
	# hier: das Zeichen ':' und alles was danach kommt
	dir=${line%:*}

	# ${VARIABLE#MUSTER} entfernt MUSTER vom Anfang des Textes in VARIABLE
	# hier: das Zeichen ':' und alles was davor kommt
	pct=${line#*:}

    if [ $pct -gt threshold ]
    then
        echo Filesystem $dir ist zu ${pct}% voll!
    fi
done
