#!/bin/bash     
#title          :countdown2
#description    :Zählt vom Wert in $1 auf 0 herunter und gibt dann Start! aus
#author         :Jochen Reinholdt
#date           :20180619
#version        :1      
#usage          :./countdown2
#notes          :Verbessert countdown1: Prüft Anzahl Parameter, Wertebereicn
#		 gibt returncode zurück
#bash_version   :3.2.57(1)-release
#============================================================================

# Prüfung Anzahl Parameter = 1?
if [ $# -ne 1 ]
then
	echo Benutzung: $0 startwert
	exit 1
fi

# Prüfung Parameter eine Zahl?
# Prüfung auf numerische Gleichheit ergibt 
# immer einen Returcode !=0, wenn keine Zahl vorliegt
if [ $# == $# ]
then
	echo Benutzung: $1 ist keine Zahl
	exit 2
fi

 
# Prüfung Startwert > 0?
if [ $# -le 0 ]
then
	echo Benutzung: startwert muss grösser als 0 sein
	exit 3
fi

zaehler=$1

while [ $zaehler -ge 0 ]
do
	echo $zaehler
	let zaehler=$zaehler-1
done

echo Start!
