#!/bin/bash     
#title          :dreieck
#description    :Gibt in einer for-schleife soviel sterne aus,
#	 	 wie in Parameter1 angegeben ist
#author         :Jochen Reinholdt
#date           :20180619
#version        :1      
#usage          :./dreieck anzahl
#notes          :       
#bash_version   :3.2.57(1)-release
#============================================================================

# Schleife über die Zeilen
for (( zeile=1; zeile<=$1; zeile++ ))
do
    # Schleife über die Spalten einer Zeile 
	for (( spalte=1; spalte <= $zeile; spalte++ ))
	do
        # Ein Stern zur Zeit wird ausgegeben
		echo -n \*
	done
	echo
done
