#!/bin/bash     
#title          :functest2
#description    :Demo Funktion mit Argumenten
#author         :Jochen Reinholdt
#date           :20180820
#version        :1.0    
#usage          :./functest2
#notes          :       
#bash_version   :3.2.57(1)-release
#============================================================================

summe() {
    sum=0
    for i in $@
    do
		let sum=sum+$i
    done
    echo $sum
    return 0
}

summe 1 2 3 4

