#!/bin/bash     
#title          :paramtest5
#description    :Prüft, wieviele  Parameter übergeben wurden und gibt diese aus
#author         :Jochen Reinholdt
#date           :20180618
#version        :1      
#usage          :./paramtest5 parameterliste
#notes          :Benutzt while-schleife und shift
#bash_version   :3.2.57(1)-release
#============================================================================

echo Anzahl Parameter: $#
zaehler=1

while [ $zaehler -le $# ]
do
	echo Parameter $zaehler: $1
	let zaehler=$zaehler+1
	shift
done
