#!/bin/bash     
#title          :paramtest5
#description    :Prüft, wieviele  Parameter übergeben wurden und gibt diese aus
#author         :Jochen Reinholdt
#date           :20180618
#version        :1.1
#usage          :./paramtest5 parameterliste
#notes          :Benutzt while-schleife und shift
#bash_version   :3.2.57(1)-release
#============================================================================

echo Anzahl Parameter: $#

# Achtung: shift verändert auch den wert $#, also sichern wir ihn in anzahl
anzahl=$#
zaehler=1

while [ $zaehler -le $anzahl ]
do
	echo Parameter $zaehler: $1
	let zaehler=$zaehler+1
	shift
done

