#!/bin/bash     
#title          :paramtest2
#description    :Gibt den Inhalt der ersten 9 Parameter aus
#author         :Jochen Reinholdt
#date           :20180618
#version        :1      
#usage          :./paramtest2
#notes          :       
#bash_version   :3.2.57(1)-release
#============================================================================

echo Parameter: $1 $2 $3 $4 $5 $6 $7 $8 $9
