#!/bin/bash     
#title          :paramtest3
#description    :Gibt die Parameter 1-9 nacheinander aus
#author         :Jochen Reinholdt
#date           :20180618
#version        :1      
#usage          :./paramtest3 parameterliste
#notes          :       
#bash_version   :3.2.57(1)-release
#============================================================================

echo Parameter 1: $1
echo Parameter 2: $2
echo Parameter 3: $3
echo Parameter 4: $4
echo Parameter 5: $5
echo Parameter 6: $6
echo Parameter 7: $7
echo Parameter 8: $8
echo Parameter 9: $9
