#!/bin/bash     
#title          :sum_params
#description    :Prüft, wieviele  Parameter übergeben wurden und summiert sie
#author         :Jochen Reinholdt
#date           :20180618
#version        :1      
#usage          :./sum_params parameterliste
#notes          :Benutzt while-schleife, let und shift
#bash_version   :3.2.57(1)-release
#============================================================================

anzahl=$#
zaehler=0
summe=0

while [ $zaehler -lt $anzahl ]
do
    # Nur wenn $1 eine Zahl ist, wird summiert
    if [ $1 -eq $1 ]
    then
        let summe=$summe+$1
    fi
	let zaehler=$zaehler+1
	shift
done
echo $summe

