#!/bin/bash
# Name        : vergleiche
# Beschreibung: Eine vereinfachte Lösung der Aufgabe 1.5
#               ohne die Prüfung, ob beide Parameter eine
#               Zahl sind. Vollständige Lösungen in : vergleiche0
#               und vergleiche1
# Autor       : Jochen Reinholdt
# Version     : 1.0
# Datum       : 16.04.2019
# #######################################################

